export const LOAD_TOP_PHOTOS_SUCCESS = 'App/LOAD_TOP_PHOTOS_SUCCESS';
export const SELECT_ITEM = 'App/SELECT_ITEM';
export const ADD_TO_FAVOURITE = 'App/ADD_TO_FAVOURITE';
export const LOADING_STARTED = 'App/LOADING_STARTED';
export const SAVE_FAVOURITE = 'App/SAVE_FAVOURITE';
export const SELECT_FAVOURITE_ITEM = 'App/SELECT_FAVOURITE_ITEM';
export const DELETE_FAVOURITE_ITEM = 'App/DELETE_FAVOURITE_ITEM';
export const CLIENT_OFFLINE = 'App/CLIENT_OFFLINE';

